### PR TITLE
Fix CSV export for Postgres when table is sorted on related column

### LINKED ISSUE #17953: [3.x] Postgres-backed app with table columns using Illuminate\Database\Query\Expression sorts cause Export Action to fail
### Package

filament/filament

### Package Version

v3.3.41

### Laravel Version

v12.31.1

### Livewire Version

_No response_

### PHP Version

PHP 8.3.25

### Problem description

When:
- App is using Postgres
- A column, in a table, in that app, is
  - Based on a relationship to the table's resource
  - Sortable
- A user attempts an export while sorting on the related column

The `PrepareCsvExport` job throws an exception with the following message [on this line](https://github.com/filamentphp/filament/blob/3.x/packages/actions/src/Exports/Jobs/PrepareCsvExport.php#L84)
```
Object of class Illuminate\Database\Query\Expression could not be converted to string
```

The root cause of this error are the changes introduced in PR #16752. Before this change, the `unique()` method was only checking the value within the `column` array key. With the change to support `DB::raw()` orders, the unique key is a concatenation of the type (raw vs column) and the value (sql vs column name, respectively). Since there is no way to directly convert an Expression to a string, you cannot concatenate it with another string.

PR #17960 fixes this issue

**This is an issue with both v3 and v4, as the `PrepareCsvExport` class is the same in both versions.**

### Expected behavior

The export job should complete and the data therein ordered correctly.

### Steps to reproduce

1. Point a Filament app at a Postgres database
2. Create two Filament columns, in any Filament table, where one column is from the resource's table and the other column is from a related table
3. Create an exporter
4. Add an Exporter Action to that table, configured with that exporter
5. Sort the table on the related column
6. Attempt an export
7. Run `php artisan queue:work` (or set your queue driver to `sync` in your `.env` file)
8. Observe the job failure

OR

1. Download the linked reproduction repo
2. Update the `.env` file to point to a Postgres database
3. Run migrations and seeders `php artisan migrate:fresh --seed`
4. Serve up the app `php artisan serve` and sign in
5. Go to the "Users" tab
6. Sort the table on the "Role" column
7. Click the "Export" button
8. Run `php artisan queue:work` (or set your queue driver to `sync` in your `.env` file)
9. Observe the job failure

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/bstanley-pec/filament-table-order-expression-export-error

### Relevant log output

```shell
[2025-09-25 20:45:56] local.ERROR: Object of class Illuminate\Database\Query\Expression could not be converted to string {"exception":"[object] (Error(code: 0): Object of class Illuminate\\Database\\Query\\Expression could not be converted to string at /Users/user/Downloads/app-filament-issue-3.x/vendor/filament/actions/src/Exports/Jobs/PrepareCsvExport.php:84)
[stacktrace]
#0 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1780): Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport->Filament\\Actions\\Exports\\Jobs\\{closure}(Array, 0)
#1 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(885): Illuminate\\Support\\Collection->Illuminate\\Support\\{closure}(Array, 0)
#2 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}(Array, 0)
#3 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(1158): array_filter(Array, Object(Closure), 1)
#4 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(415): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#5 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(883): Illuminate\\Support\\Collection->filter(Object(Closure))
#6 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1779): Illuminate\\Support\\Collection->reject(Object(Closure))
#7 /Users/user/Downloads/app-filament-issue-3.x/vendor/filament/actions/src/Exports/Jobs/PrepareCsvExport.php(79): Illuminate\\Support\\Collection->unique(Object(Closure))
#8 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport->handle()
#9 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(96): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/Container.php(836): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Container\\Container->call(Array)
#14 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport))
#15 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport))
#16 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(136): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(134): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport), false)
#18 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport))
#19 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport))
#20 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#21 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(68): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Filament\\Actions\\Exports\\Jobs\\PrepareCsvExport))
#22 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#23 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(444): Illuminate\\Queue\\Jobs\\Job->fire()
#24 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(394): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#25 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(180): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#26 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#27 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#28 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#29 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#30 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(96): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#31 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#32 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Container/Container.php(836): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#33 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#34 /Users/user/Downloads/app-filament-issue-3.x/vendor/symfony/console/Command/Command.php(318): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#35 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#36 /Users/user/Downloads/app-filament-issue-3.x/vendor/symfony/console/Application.php(1110): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /Users/user/Downloads/app-filament-issue-3.x/vendor/symfony/console/Application.php(359): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /Users/user/Downloads/app-filament-issue-3.x/vendor/symfony/console/Application.php(194): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /Users/user/Downloads/app-filament-issue-3.x/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1235): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /Users/user/Downloads/app-filament-issue-3.x/artisan(16): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#42 {main}
"}
```

### PR DESCRIPTION
**Pull request by bstanley-pec**
## Description

Fixes #17953

## Visual changes

N/A

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by qschmick** [comment]
👍

**Comment by kithodgespec** [comment]
👍

File: packages/actions/src/Exports/Jobs/PrepareCsvExport.php [hunk 1]
```diff
@@ -76,11 +77,15 @@ public function handle(): void
 
                     return ($order['column'] ?? null) === $qualifiedKeyName;
                 })
-                ->unique(function (array $order): string {
+                ->unique(function (array $order) use ($databaseGrammar): string {
                     if (($order['type'] ?? null) === 'Raw') {
                         return 'raw:' . ($order['sql'] ?? '');
                     }
 
+                    if ($databaseGrammar->isExpression(($order['column'] ?? null))) {
```
Comment (danharrin) [inline packages/actions/src/Exports/Jobs/PrepareCsvExport.php]:
```suggestion
                    if ($databaseGrammar->isExpression($order['column'] ?? null)) {
```

**Review by danharrin — CHANGES_REQUESTED** [review]

**Review by danharrin — APPROVED** [review]
