### PR TITLE
fix #8788 - reset activerelationmanager when selected is hidden

### LINKED ISSUE #8788: Issue when toggling a resources relationmanager
### Package

filament/filament

### Package Version

v3.0.62

### Laravel Version

v10.25.2

### Livewire Version

v3.0.5

### PHP Version

PHP 8.2.5

### Problem description

Having two relationmanagers on a resource, one with canViewForRecord(), controlled by an  $ownerRecord attribute, e.g. a boolen toggle.

switch off the toggle,save record -> all relationmanagers disappear with js error : "Uncaught Snapshot missing on Livewire component with id: cdUvjw37Lpwhz4xgoRYE"

switch on the toggle, save record -> tablist nav item is shown, but relationmanager tabpanel has empty livewire component, also js error: "Uncaught Snapshot missing on Livewire component with id: JBybPURsFHmsJocGGswn"

### Expected behavior

tabbed relationmanagers to appear when controller attribute is set, or remove tabbed manager and show single relationmanager when attribute is unset

### Steps to reproduce

add Toggle to a form of a resource with two relationmanagers

```
public static function getRelations(): array
{
        return [
            RelationManagers\AddressesRelationManager::class,
            RelationManagers\PaymentsRelationManager::class,
        ];
}
```

```
Forms\Components\Toggle::make('has_payments')
```

define canViewForRecord method on one of the managers

```
public static function canViewForRecord(Model $ownerRecord, string $pageClass): bool
    {
        return $ownerRecord->has_payments;
    }
```

### Reproduction repository

https://github.com/tvdr/filamentdemo/tree/tabbed_relationmanager_fix

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tvdr**
This PR fixes the bug described in https://github.com/filamentphp/filament/issues/8788 considering @danharrin 's [comment](https://github.com/filamentphp/filament/pull/8790#issuecomment-1763314753)  

After hiding a currently active relation manager, the activeRelationManager is set to the first item and viewdata is updated before rendering.

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.

### CODE REVIEW

File: packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php [hunk 1]
```diff
@@ -55,6 +56,16 @@ public function mountHasRelationManagers(): void
         $this->activeRelationManager = array_key_first($this->getRelationManagers()) ?? null;
     }
 
+    public function renderingHasRelationManagers(View $view): void
+    {
+        $managers = $this->getRelationManagers();
+
+        if (!array_key_exists($this->activeRelationManager, $managers) && !$this->hasCombinedRelationManagerTabsWithContent()) {
+            $this->activeRelationManager = array_key_first($this->getRelationManagers()) ?? null;
+            $view->with('activeRelationManager', $this->activeRelationManager);
```
Comment (danharrin) [inline packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php]: Is this line needed? I think that all public properties are exposed to the view by default

Comment (tvdr) [reply packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php]: i'm not sure if i fully understand how the full lifecycle here works, but without setting the View-s data here, only after a following update request will the active tab set to the first item.

while trying to figure this out, i found that in the edit-record.blade.php there is a difference between $this->activeRelationManager and $activeRelationManager, (accessing the property via $this return the desired value without setting it on the viewdata) 
but can't find anything about this in the docs. i'm not sure if this is a bad pattern to rely on.

so passing :active-manager="$this->activeRelationManager to  <x-filament-panels::resources.relation-managers works, but i don't want to submit something that is not acceptable.

Comment (danharrin) [reply packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php]: I've switched to `$this->activeRelationManager`, that should be fine
