### PR TITLE
fix: add cancel upload functionality to file upload component

### LINKED ISSUE #15844: "tap to cancel" not working in `FileUpload` form field
### Package

filament/filament

### Package Version

v3.3.4

### Laravel Version

v11.44.1

### Livewire Version

_No response_

### PHP Version

PHP 8.2

### Problem description

Hi, I'm using the `FileUpload` form field to upload larger files and I noticed that the "tap to cancel" field on the uploader is not working at all. This is also true for the `SpatieMediaFileUpload` field. I have checked the filepond demos where it works as expected, so it does not seem to be a filepond bug. I'm not sure if this is CSS, JS or even browser related. I've tested Chrome, Firefox and Edge and it's not working in any browser for me.

Image

### Expected behavior

Successfully cancel the file upload while uploading.

### Steps to reproduce

- navigate to the `CreateOrder` form
- (optional) throttle network speed (for more time)
- upload a large-ish file in the `FileUpload` field
- try to cancel the upload while uploading

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/c-zehnter/fileupload

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by People-Sea**
## Description

fixes: #15844

## Visual changes

# Before

https://github.com/user-attachments/assets/78f61000-1e9f-4923-9dd5-1e03a795b272

# After

https://github.com/user-attachments/assets/beba5dea-87b5-47a5-9333-95facd38cf43

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/forms/resources/js/components/file-upload.js [hunk 1]
```diff
@@ -75,6 +75,7 @@ export default function fileUploadFormComponent({
     uploadingMessage,
     uploadProgressIndicatorPosition,
     uploadUsing,
+    cancelUploadFileUsing,
```
Comment (danharrin) [inline packages/forms/resources/js/components/file-upload.js]: Please inject these new parameters in alphabetical order

**Review by danharrin — CHANGES_REQUESTED** [review]

File: packages/forms/resources/js/components/file-upload.js (hunk 1 above)
Comment (danharrin) [reply packages/forms/resources/js/components/file-upload.js]: Please also rename this to `cancelUploadUsing`

**Review by danharrin — APPROVED** [review]
Very sorry, when I asked about the alphabetical thing I didn't realise that most of the list is not already alphabetical 🤣 Thanks

This is a great contribution, well done
