### PR TITLE
[4] Replace Legacy Tailwind CSS v3 screen function

### LINKED ISSUE #16800: [v4] Legacy Tailwind CSS v3 `screen` function used in `file-upload.css`
### Package

filament/filament

### Package Version

v4.0.0-beta12

### Laravel Version

v12.19.3

### Livewire Version

v3.6.3

### PHP Version

8.3.6

### Problem description

I've noticed that the CSS for the file upload component uses the `screen` function, which was a feature of Tailwind CSS v3 and is no longer supported in Tailwind CSS v4.

**File:** `vendor/filament/forms/resources/css/components/file-upload.css`

**Problematic Code:**
``` css
@media screen(lg) {
    & .filepond--root[data-style-panel-layout='grid'] .filepond--item {
        width: calc(33.33% - 0.5rem);
    }
}
```

Note:
`@media screen()` was only used in file-upload.css as of now.

### Expected behavior

After further research It was suggested to use the following:

```css

@reference "tailwindcss"; //Added Globally Once

.fi-fo-file-upload {
    @variant lg {
        & .filepond--root[data-style-panel-layout='grid'] .filepond--item {
            width: calc(33.33% - 0.5rem);
        }
    }
}

```

Not sure if its the right approach.

Reference:
https://github.com/tailwindlabs/tailwindcss/discussions/15960

### Steps to reproduce

Using the following Form

```php
            SpatieMediaLibraryFileUpload::make('upload')
                ->panelLayout('grid')
                ->multiple()
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by malzariey**
## Description

Fixes #16800 

## Visual changes

None

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/support/src/View/Concerns/CanGenerateButtonHtml.php
Comment (danharrin) [inline packages/support/src/View/Concerns/CanGenerateButtonHtml.php:1]: Can you please revert the spacing change here?

File: packages/forms/resources/css/index.css [hunk 1]
```diff
@@ -18,3 +18,4 @@
 @import './components/text-input.css' layer(components);
 @import './components/textarea.css' layer(components);
 @import './components/toggle-buttons.css' layer(components);
+@reference "tailwindcss";
```
Comment (danharrin) [inline packages/forms/resources/css/index.css]: Can you please explain what this is for?

**Review by danharrin — CHANGES_REQUESTED** [review]

File: packages/forms/resources/css/index.css (hunk 1 above)
Comment (malzariey) [reply packages/forms/resources/css/index.css]: To utilize Tailwind CSS's default variants (like lg) within filament's CSS files, we must either reference the theme.css using ``` @reference "tailwindcss";```  where they are defined or globally redefine these variants. Failing to do so will result in a build error:
```css
error during build:
[@tailwindcss/vite:generate:build] Cannot use `@variant` with unknown variant: lg  
```

Varients defination example :
```css
/*In tailwindcss theme.css */
@theme default {
    --breakpoint-sm: 40rem;
    --breakpoint-md: 48rem;
    --breakpoint-lg: 64rem;
    --breakpoint-xl: 80rem;
    --breakpoint-2xl: 96rem;
}
```

References:
https://tailwindcss.com/docs/functions-and-directives#reference-directive
https://tailwindcss.com/docs/upgrade-guide#using-apply-with-vue-svelte-or-css-modules

Comment (malzariey) [reply packages/forms/resources/css/index.css]: What would you prefer regarding breakpoint variants:

Would it be better to add them directly to Filament's theme.css, or to use @reference "tailwindcss"; or import Tailwind's theme.css within Filament's theme.css

Comment (danharrin) [reply packages/forms/resources/css/index.css]: I don't really understand Tailwind's reasoning here, why does it know what `p-3` is in the same file but not know `variant lg`. I believe you, its just weird.

File: packages/support/src/View/Concerns/CanGenerateButtonHtml.php
Comment (malzariey) [reply packages/support/src/View/Concerns/CanGenerateButtonHtml.php:1]: Sorry didnt notice the request.

Comment (malzariey) [reply packages/support/src/View/Concerns/CanGenerateButtonHtml.php:1]: wouldnt the `composer cs` do it again if removed?

File: packages/forms/resources/css/index.css (hunk 1 above)
Comment (danharrin) [reply packages/forms/resources/css/index.css]: I just tried myself and it worked without the reference, so I have removed it

**Review by danharrin — APPROVED** [review]

File: packages/forms/resources/css/index.css (hunk 1 above)
Comment (malzariey) [reply packages/forms/resources/css/index.css]: > I just tried myself and it worked without the reference, so I have removed it

Using `npm run build` ?

Comment (danharrin) [reply packages/forms/resources/css/index.css]: Yup, no issues there. Make sure your NPM dependencies are up to date maybe

Comment (malzariey) [reply packages/forms/resources/css/index.css]: Apologize for the inconvenience
