### PR TITLE
Fix for bug #12115

### LINKED ISSUE #12115: Filament\Tables\Table::getInverseRelationshipFor(): Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model
### Package

filament/filament

### Package Version

v3.2.0

### Laravel Version

v10.0.0

### Livewire Version

_No response_

### PHP Version

PHP 8.2.17

### Problem description

I am trying to use Associate::make()->multiple on a HasMany - BelongsTo relation. 

Searching and picking works fine, but as soon as I hit save I get the error. If I removed multiple() it will work fine.

Please keep in mind that I had to put 

### Expected behavior

Expected to save correctly.

### Steps to reproduce

My models are as follows

```
class Company extends Model
{
    use HasFactory;

     public function users(): HasMany
     {
	return $this->hasMany(User::class);
     }

}
```

And in User Model

```
public function company(): BelongsTo
{
	return $this->belongsTo(Company::class);
}
```

I ran this to produce the relation manager
`php artisan make:filament-relation-manager CompanyResource users name --associate
` 
And my code in the relation manager table() function is as follows

```
            ->headerActions([
                Tables\Actions\AssociateAction::make()->multiple()
            ])
```

### Reproduction repository

https://github.com/classicalguss/curly-disco

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dmitry-udod**
## Description

Fix for bug #12115 

https://github.com/filamentphp/filament/assets/4639175/d482d4fa-c7a3-4e8f-b7f9-a24498847797

Before proposed fix

https://github.com/filamentphp/filament/assets/4639175/547ce979-892f-4af6-b134-9599f383e44f

## Visual changes

Nope

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/tables/src/Actions/AssociateAction.php [hunk 1]
```diff
@@ -75,21 +75,24 @@ protected function setUp(): void
...
             $record = $relationship->getQuery()->find($data['recordId']);
+            $records = $this->isMultiple ? $record : collect([$record]);
 
-            if ($record instanceof Model) {
-                $this->record($record);
-            }
-
-            /** @var BelongsTo $inverseRelationship */
-            $inverseRelationship = $table->getInverseRelationshipFor($record);
+            $records->each(function ($record) use ($table, $relationship) {
```
Comment (danharrin) [inline packages/tables/src/Actions/AssociateAction.php]: Can we replace this with a simple `foreach ($this->isMultiple ? $record : [$record]) {` please? Then we don't need to bother with the extra closure function and passing in the vars from the parent scope?

Comment (dmitry-udod) [reply packages/tables/src/Actions/AssociateAction.php]: Sure. Done.

**Comment by danharrin** [comment]
Thanks!
