### PR TITLE
Fix widget make command

### LINKED ISSUE #8835: `MakeWidgetCommand` not working with latest versions of `laravel/prompts`
### Package

filament/widgets

### Package Version

v3.0.63

### Laravel Version

v10.25.2

### Livewire Version

v3.0.5

### PHP Version

8.2

### Problem description

Not sure if it's a [recent change](https://github.com/laravel/prompts/pull/84/files) in the `laravel/prompts` package or something else, but the `make:filament-widget` commands doesn't work if you select the default option on the "_Where would you like to create this?_" step and always returns a __Require__ validation error.

image

Changing the code in 

```filament/widgets/src/Commands/MakeWidgetCommand.php:86```

To 
```php 
'App\Livewire' => '[App\\Livewire] alongside other Livewire components',
```
(or any other truthy value for the key) seems to solve the issue.

### Expected behavior

You should be able to create widgets by selecting the only given option on the "_Where would you like to create this?_" step of the command

### Steps to reproduce

1. Use the latest versions of laravel and filament
2. Try running the `php artisan make:filament-widget Test` command
3. Don't create the widget inside a resource (step 1 of the prompt)
4. Select `App\Livewire` in the 2nd prompt
5. 2 files should be created. Instead, you'll get a validation error

Unfortunately, I could only partially reproduce this

Running this under Windows 10 and Powershell, it seems to work as expected, but the prompt looks different (attached screenshot).
image

### Reproduction repository

https://github.com/sprtk-ches/laravel-filament

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by cheesegrits**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

A recent change to select() in Prompts is breaking the usage in make-widget, whereby a select option cannot be empty, and required(false) no longer works for select().  The fix for this is to name the additional option in the make-widget panel selection.

There is also another "bug", whereby the make fails if the user's Livewire namespace is not App/Livewire, for example if they have updated from v2 to v3 and elected not to move from App/Http/Livewire.  The fix for this is to use config('livewire.class_namespace') for deriving the path and namespace.

### CODE REVIEW

**Comment by sprtk-ches** [comment]
Closes #8835

File: packages/widgets/src/Commands/MakeWidgetCommand.php [hunk 1]
```diff
@@ -95,8 +96,8 @@ public function handle(): int
         $resourceNamespace = null;
 
         if (! $panel) {
-            $path = app_path('Livewire/');
-            $namespace = 'App\\Livewire';
+            $namespace = config('livewire.class_namespace');
+            $path = app_path(Str::of($namespace)->after('App\\')->replace('\\', '/')->toString());
```
Comment (danharrin) [inline packages/widgets/src/Commands/MakeWidgetCommand.php]:
```suggestion
            $path = app_path((string) str($namespace)->after('App\\')->replace('\\', '/'));
```
