### PR TITLE
V4 fix reorderable columns

### LINKED ISSUE #16720: Displayed column order does not match the order specified in the Table columns array
### Package

filament/filament

### Package Version

v4.0.0-beta10

### Laravel Version

v12.19.3

### Livewire Version

_No response_

### PHP Version

8.3.22

### Problem description

When creating a table in the filament panel , changing the order of the columns in the array  does not  change the order displayed in the panel. any new columns are added at the end on the table even if it is at the beginning of the columns array.
Tor example : 
this table  array 
```php
<?php

namespace App\Filament\Resources\Categories\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class CategoriesTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('slug')
                    ->label('Slug')
                    ->sortable()
                    ->searchable(),
                TextColumn::make('description')
                    ->label('Description')
                    ->limit(50) // Limit the description to 50 characters
                    ->searchable(),
                TextColumn::make('name')
                    ->label('Category Name')
                    ->sortable()
                    ->searchable(),

                TextColumn::make('icon')
                    ->label('Icon')
                    ->sortable()
                    ->searchable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}

```
renders this table which is obviously wrong
Image

### Expected behavior

columns are rendered in the same order in the columns array

### Steps to reproduce

- create a new laravel project 
- install filament beta
- create a table with multiple columns

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/nabileisa/filament4-beta10-bug

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by archilex**
Fixes #16720. Also, adds a reset button to reset the table to it's default state (ie, the state determined by the dev).

These changes also brought speed improvements when initializing the column manager when reoderable columns are not enabled, or when they are but the user hasn't reordered any columns. From 0.13 ms to 0.08 ms.

@danharrin to fix this behavior, new methods were introduced and to keep naming clear and consistent, I renamed other methods/variables to be consistent. Feel free to work your naming magic.

Also, I hope to build out a test suite for all this functionality in the near future to make sure future changes don't break current functionality.

- [X] Code style has been fixed by running the `composer cs` command.
- [X] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

File: packages/tables/src/Concerns/HasColumnManager.php [hunk 1]
```diff
@@ -21,6 +21,11 @@ trait HasColumnManager
      */
     public array $tableColumns = [];
 
+    /**
+     * @var ?array<int, array{type: string, name: string, label: string, isToggled: bool, isToggleable: bool, columns?: array<int, array{type: string, name: string, label: string, isToggled: bool, isToggleable: bool}>}>
+     */
+    public ?array $cachedDefaultTableColumnState = null;
```
Comment (danharrin) [inline packages/tables/src/Concerns/HasColumnManager.php]: This looks good and seems to work great, my only question is about this property. Does it need to be persisted between Livewire requests or can it be rebuilt? I think it can probably be protected, or it should be `#[Locked]` so it cant be tampered with on the frontend?

**Review by danharrin — CHANGES_REQUESTED** [review]
The only real name changes I needed to make were to do with adding `table` to the names of methods. When we are adding new methods to traits like `InteractsWithTables`, which get added to classes in the users own codebase, we need to try and minimise clashes with any methods they already have. Names like `findMatchingItem()` are going to more likely clash with other methods than `findMatchingTableColumnStateItem()`. For methods that exist on Filament internal classes I worry less about this.

File: packages/tables/src/Concerns/HasColumnManager.php (hunk 1 above)
Comment (archilex) [reply packages/tables/src/Concerns/HasColumnManager.php]: Fixed. It should be protected. I had made it public when I was debugging and forgot to switch it back. And I'm only caching it for the request since multiple methods need to access this and this was cleaner than passing a variable between a bunch of methods.

**Review by danharrin — APPROVED** [review]

**Comment by danharrin** [comment]
Thanks!
