### PR TITLE
Fix bug #12342

### LINKED ISSUE #12342: Database Notifications is not displayed correctly due to the ListPage parameter page=2 when the `$isPaginated` option is active
### Package

filament/filament

### Package Version

v3.2.65

### Laravel Version

10.48.7

### Livewire Version

3.4.10

### PHP Version

8.2

### Problem description

Database notifications do not appear when we have a page=2 parameter in the url on the ListRecord page. From what I understand, the Filament\Notifications\Livewire::getNotifications() method returns paginated results and the url parameter affects notifications, when it should only affect ListRecord results.

### Expected behavior

 View notifications regardless of the parameter provided in the ListPage

### Steps to reproduce

1) Run the command php artisan migrate:fresh --seed
2) Login with e-mail `filament@test.com` and password `123456`
3) Go to "Users" page
4) Click in "2" pagination
5) Refresh page
6) Open the notifications

### Reproduction repository

https://github.com/wallacemaxters/filament-bug-report

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dmitry-udod**
## Description

Proposal for fix bug #12342 

## Visual changes

Nope

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/notifications/src/Livewire/DatabaseNotifications.php [hunk 1]
```diff
@@ -74,7 +74,7 @@ public function getNotifications(): DatabaseNotificationCollection | Paginator
             return $this->getNotificationsQuery()->get();
         }
 
-        return $this->getNotificationsQuery()->simplePaginate(50);
+        return $this->getNotificationsQuery()->simplePaginate(50, pageName: 'notifications-page');
```
Comment (danharrin) [inline packages/notifications/src/Livewire/DatabaseNotifications.php]:
```suggestion
        return $this->getNotificationsQuery()->simplePaginate(50, pageName: 'database-notifications-page');
```

**Comment by danharrin** [comment]
Thanks!
