### PR TITLE
fix: allow to access default page for non-auth panel

### LINKED ISSUE #13379: Infinite redirect loop
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v11.11.1

### Livewire Version

v3.5.1

### PHP Version

PHP 8.3.8

### Problem description

I'm building a panel without login and without default Dashboard page.
I've removed `->login()` from `AdminPanelProvider` and now once I remove `->pages([Pages\Dashboard::class])` from `AdminPanelProvider` I'm getting infinite redirect loop when trying to access the panel root url, however if I try to access any resource, e.g. `/users` I can access it without any issues, the issue happens only with the root `/` url. 

In case Login is needed (`->login()` call exists in `AdminPanelProvider`), everything works fine — after successful login I'm being redirected to the first navigation menu item page even if I have Dashboard removed from `AdminPanelProvider`.

### Expected behavior

I've expected root `/` url would redirect to the first navigation item page in case there's no Dashboard, same as if login is needed to access the panel.

### Steps to reproduce

Install fresh Filament Panel Builder, create any Resource, remove `->login()` call from `AdminPanelProvider`, remove `->pages([Pages\Dashboard::class])` from `AdminPanelProvider`. Try to open admin panel by root url, e.g. `http://filament.test/`.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/plakhin/filament-issue

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by smiliyas**
## Description

closes #13379

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

File: packages/panels/src/Panel/Concerns/HasRoutes.php [hunk 1]
```diff
@@ -167,8 +167,8 @@ public function getPath(): string
 
     public function getUrl(?Model $tenant = null): ?string
     {
-        if (! $this->auth()->check()) {
-            return $this->hasLogin() ? $this->getLoginUrl() : url($this->getPath());
+        if (! $this->auth()->check() && $this->hasLogin()) {
```
Comment (danharrin) [inline packages/panels/src/Panel/Concerns/HasRoutes.php]:
```suggestion
        if ((! $this->auth()->check()) && $this->hasLogin()) {
```

**Review by danharrin — CHANGES_REQUESTED** [review]

**Comment by danharrin** [comment]
Thanks
