### PR TITLE
Fix: image and markdown persisting state

### LINKED ISSUE #4207: File upload isn't cleared after create and add another
### Package

filament/filament

### Package Version

^2.15

### Laravel Version

^9.19

### Livewire Version

_No response_

### PHP Version

^8.0.2

### Problem description

file upload isn't cleared after create and add another 

### Expected behavior

Clear files after submit create and add another
Screenshot 2022-09-26 at 15 52 24

### Steps to reproduce

Create a Product
Add a image
Click Create & Create Another

 "php": "^8.0.2",
"doctrine/dbal": "^3.3",
"filament/filament": "^2.0",

### Reproduction repository

https://github.com/filamentphp/demo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by awcodes**
Resolves #4207.

### CODE REVIEW

File: packages/forms/resources/js/components/markdown-editor.js [hunk 1]
```diff
@@ -24,7 +24,10 @@ export default (Alpine) => {
                     })
                 }
 
-                this.$watch('state', () => {
+                this.$watch('state', (value) => {
+                    if (value === null) {
+                        this.state = ''
+                    }
                     this.render()
```
Comment (zepfietje) [inline packages/forms/resources/js/components/markdown-editor.js:32]:
```suggestion

                    this.render()
```

File: packages/forms/resources/js/components/file-upload.js [hunk 2]
```diff
@@ -179,6 +179,7 @@ export default (Alpine) => {
                                 file.startsWith('livewire-file:'),
                             ).length
                         ) {
+                            this.lastState = null
                             return
```
Comment (zepfietje) [inline packages/forms/resources/js/components/file-upload.js:185]:
```suggestion

                            return
```

**Review by zepfietje — DISMISSED** [review]

File: packages/forms/resources/js/components/file-upload.js [hunk 3]
```diff
@@ -179,6 +179,8 @@ export default (Alpine) => {
                                 file.startsWith('livewire-file:'),
                             ).length
                         ) {
+                            this.lastState = null
```
Comment (danharrin) [inline packages/forms/resources/js/components/file-upload.js:183]: Unfortunately this didnt fix the problem for me? Try the Create Product page in the demo.

Comment (awcodes) [reply packages/forms/resources/js/components/file-upload.js:183]: Weird works on the create blog post page for me.

Comment (awcodes) [reply packages/forms/resources/js/components/file-upload.js:183]: What would be different about those?

Comment (danharrin) [reply packages/forms/resources/js/components/file-upload.js:183]: Can you confirm that it doesnt work for products though or is that just me?

Comment (zepfietje) [reply packages/forms/resources/js/components/file-upload.js:183]: It doesn't work on the products page for me, while it does work on the blog post page.

Comment (awcodes) [reply packages/forms/resources/js/components/file-upload.js:183]: I'll see if I can figure it out today.

Comment (awcodes) [reply packages/forms/resources/js/components/file-upload.js:183]: So, this is something to do with the product page / resource and i'm not sure what it could be.

https://user-images.githubusercontent.com/3596800/195993445-63062d96-b75d-4f71-ac54-539819613d3b.mov

Comment (awcodes) [reply packages/forms/resources/js/components/file-upload.js:183]: Oddly enough, without the fix. The Spatie upload clears correctly.

Comment (awcodes) [reply packages/forms/resources/js/components/file-upload.js:183]: Latest commit addresses the issue on the product page. For some reason on that resource the media field is coming back as null after saving which the JS can't convert to an object to perform the necessary check for if the file list has changed or not.

**Comment by zepfietje** [comment]
Is this PR ready for review now, @awcodes?
If so, you can mark it as ready. 🙂

**Comment by awcodes** [comment]
I wasn't sure if it was ready for review or not. Was waiting to see if there was any input about the spatie upload returning null on the product page and not anywhere else. 

I'm hesitant to push a fix even though it works if it masks an underlying bug with another component.

**Comment by danharrin** [comment]
Thanks
