### PR TITLE
fix: Recursively attach relationship with pivot ID

### LINKED ISSUE #10568: Incrementing ID in Pivot Table Causes Issue in Recursive Relationship
### Package

filament/filament

### Package Version

v3.1.31

### Laravel Version

v10.39.0

### Livewire Version

_No response_

### PHP Version

PHP 8.2

### Problem description

I've identified a bug in the Filament framework, which seems to have been introduced in PR 10078 (https://github.com/filamentphp/filament/pull/10078). This bug is relevant to [Issue #8067](https://github.com/filamentphp/filament/issues/8067) and arises under specific circumstances.

**Actual Behavior:**
An error or unexpected behavior (further details to be provided) occurs due to the incrementing ID in the pivot table.

**Impact:**
This issue may affect applications that rely on self-referential relationships with incrementing IDs in pivot tables.

**Additional Context:**

Link to PR introducing the bug: [PR 10078](https://github.com/filamentphp/filament/pull/10078)
Original issue related to this bug: [Issue #8067](https://github.com/filamentphp/filament/issues/8067)

**Example migration:**

```php
Schema::create('tasks', function (Blueprint $table) {
    $table->id();
    $table->timestamps();

    $table->string('name');
});

Schema::create('task_edges', function (Blueprint $table) {
    $table->id();
    $table->foreignId('parent_id')->references('id')->on('tasks');
    $table->foreignId('child_id')->references('id')->on('tasks');

    $table->unique(['parent_id', 'child_id']);
});
```

Example relationships:

```php
    public function childTasks(): BelongsToMany
    {
        return $this->belongsToMany(Task::class, 'task_edges', 'parent_id', 'child_id');
    }

    public function parentTasks(): BelongsToMany
    {
        return $this->belongsToMany(Task::class, 'task_edges', 'child_id', 'parent_id');
    }
```

The bug is triggered when an RelationManager attempts to Attach a relationship via the AttachAction.

```
Tables\Actions\AttachAction::make()->preloadRecordSelect(),
```

### Expected behavior

Normal operation of the parent-child table relationship, irrespective of the pivot table's ID configuration.

### Steps to reproduce

1. Use a scenario where parent and child tables are identical.
2. Ensure the pivot table connecting these tables has an incrementing ID.

### Reproduction repository

https://github.com/dennisvandalen/filament-recursive-attach-relationship-with-id

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dennisvandalen**
## Description

An error occurs due to the incrementing ID in the pivot table while trying to Attach a record via the AttachAction.

Fixes https://github.com/filamentphp/filament/issues/10568

Impact:
This issue may affect applications that rely on self-referential relationships with incrementing IDs in pivot tables.

Reproduction repository:
https://github.com/dennisvandalen/filament-recursive-attach-relationship-with-id

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been manually tested.

## Documentation

No new features.

### CODE REVIEW

File: packages/tables/src/Actions/AttachAction.php [hunk 1]
```diff
@@ -227,6 +227,7 @@ public function getRecordSelect(): Select
                 });
             }
 
+            $relationCountHash = $relationship->getRelationCountHash(false);
```
Comment (danharrin) [inline packages/tables/src/Actions/AttachAction.php]:
```suggestion
            $relationCountHash = $relationship->getRelationCountHash(incrementJoinCount: false);
            
```

File: packages/tables/src/Actions/AssociateAction.php [hunk 2]
```diff
@@ -223,8 +223,12 @@ public function getRecordSelect(): Select
                 });
             }
 
+            $relationCountHash = $relationship->getRelationCountHash(false);
```
Comment (danharrin) [inline packages/tables/src/Actions/AssociateAction.php]:
```suggestion
            $relationCountHash = $relationship->getRelationCountHash(incrementJoinCount: false);
            
```

File: packages/tables/src/Actions/AssociateAction.php [hunk 3]
```diff
@@ -240,7 +245,7 @@ public function getRecordSelect(): Select
                     return $query->where(
                         // https://github.com/filamentphp/filament/issues/8067
                         $relationship->getParent()->getTable() === $relationship->getRelated()->getTable() ?
-                            $relationship->getParent()->getKeyName() :
+                            ($relationCountHash . '.' . $relationship->getParent()->getKeyName()) :
```
Comment (danharrin) [inline packages/tables/src/Actions/AssociateAction.php]:
```suggestion
                            "{$relationCountHash}.{$relationship->getParent()->getKeyName()}" :
```

File: packages/tables/src/Actions/AttachAction.php [hunk 4]
```diff
@@ -235,7 +237,7 @@ public function getRecordSelect(): Select
                         fn (Builder $query): Builder => $query->where(
                             // https://github.com/filamentphp/filament/issues/8067
                             $relationship->getParent()->getTable() === $relationship->getRelated()->getTable() ?
-                                $relationship->getParent()->getKeyName() :
+                                ($relationCountHash . '.' . $relationship->getParent()->getKeyName()) :
```
Comment (danharrin) [inline packages/tables/src/Actions/AttachAction.php]:
```suggestion
                                "{$relationCountHash}.{$relationship->getParent()->getKeyName()}" :
```

**Comment by danharrin** [comment]
Thanks!

**Comment by dennisvandalen** [comment]
> Thanks!

Thanks for merging! Happy new year 🎆
