### PR TITLE
Fix custom notification object

### LINKED ISSUE #9268: Custom notifications do not persist state
### Package

filament/notifications

### Package Version

v3.0.83

### Laravel Version

v10.28.0

### Livewire Version

v3.0.10

### PHP Version

v8.2.11

### Problem description

Using custom notifications as detailed in the docs, the state of a custom property within a custom notification is not maintained.

### Expected behavior

The state to be maintained.

### Steps to reproduce

Repo included. The notification on the Settings page dumps the state of the notification which includes the default "size" property and not the one specified. The test at tests/Feature/SettingsTest.php also shows that the state is not maintained.

Related, the test shows that the "actual" result is correct when the "expected" is incorrect. I think this is down to the assertion rather than the `Notification`.

I started a discussion at https://github.com/filamentphp/filament/discussions/8719 which is related and indicates the possible culprit.

### Reproduction repository

https://github.com/titantwentyone/filament-custom-notification-issue

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by wychoong**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

closes #9268 

when recreating the notification object from array, `Notification` class resolved the correct `CustomNotification` but the `CustomNotification::fromArray` is not called again. this PR fixes that by checking if the notification object resolved from container is custom and its called from `Notification` class to ensure its only called once and prevent infinite loop

another approach would be in livewire\Notifications to resolved the notification object but that would have multiple useless instance created and more code changes that I not able to test

### CODE REVIEW

**Comment by danharrin** [comment]
Duplicate of #9299?

**Comment by wychoong** [comment]
> Duplicate of #9299?

Fixed the same issue without exposing unnecessary info

**Comment by danharrin** [comment]
I don't think I understand how it works?

**Comment by wychoong** [comment]
> I don't think I understand how it works?

in this file
https://github.com/filamentphp/filament/blob/73d6c1c42f10407455c689902e93171fe4086912/packages/notifications/src/Livewire/Notifications.php#L35-L42

`Notification::fromArray($notification)` is `Filament\Notifications\Notification`

here it will return the `CustomNotification` from the `make` method
https://github.com/filamentphp/filament/blob/73d6c1c42f10407455c689902e93171fe4086912/packages/notifications/src/Notification.php#L88-L91

and it continues to configure the object with the array data, thus it never gets to call to `CustomNotification::fromArray`, this can be verified by `dd` in `CustomNotification::fromArray`

with this fix
```php
if (is_subclass_of($static::class, self::class) && get_called_class() === self::class) {
    $static = $static::fromArray($data);
}
```
it checks if the `$static` notification class is extended from the base `Notification`.
And also make sure it is called from `Notification`. This is because we need to call `parent::fromArray` in the `CustomNotification` to ensure the rest of properties are set. 
Without these checks it will be infinite loops as `base->custom->base->custom->...`

File: packages/notifications/src/Notification.php [hunk 1]
```diff
@@ -88,6 +88,11 @@ public function toArray(): array
     public static function fromArray(array $data): static
     {
         $static = static::make($data['id'] ?? Str::random());
```
Comment (danharrin) [inline packages/notifications/src/Notification.php:90]: Shouldn't the `make()` method instantiate a new CustomNotification from the container, instead? I think thats the original idea behind binding it to the container

Comment (wychoong) [reply packages/notifications/src/Notification.php:90]: it does get the CustomNotification, this is not wrong, but as it only gets it here, the `CustomNotification::fromArray` is not called at all

Comment (wychoong) [reply packages/notifications/src/Notification.php:90]: in `Livewire\Notifications`
```php
// before fix
Notification::fromArray
   > `make()` return `CustomNotification`
   > set properties to `CustomNotification` with Notification's definition
   > return to lw

$this->push into collection
```

```php
// after fix
Notification::fromArray
   > `make()` return `CustomNotification`
   > call `CustomNotification::fromArray`
        > call `parent:fromArray`
        > run `CustomNotification` logic
   > return to lw

$this->push into collection
```

maybe this is clearer?

**Comment by danharrin** [comment]
Thanks!
