### PR TITLE
Fixed bug issue on TextArea with autosize after validation failed

### LINKED ISSUE #11428: Autosize textarea doesn't work after form validation failed
### Package

filament/forms

### Package Version

v3.2.28

### Laravel Version

v10.43.0

### Livewire Version

_No response_

### PHP Version

PHP 8.2

### Problem description

the textarea return to its original height after validation failed

### Expected behavior

the textarea should remain same height after validation failed

### Steps to reproduce

1. Make a autosize textare
2. Validate textarea content row by row (i'm validate url with line number)
3. Given non url text
4. Bug!

### Reproduction repository

x

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by emamalias**
## Description

Reference issue #11428 

Fixes bug issue on TextArea form component with autosize() return the height to initial height after validation failed

## Visual changes

https://github.com/filamentphp/filament/assets/13638285/e22ea86a-2e85-4faf-bb01-f2456f4ae672

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Review by danharrin — CHANGES_REQUESTED** [review]
Please revert the change to `x-bind`, the properties can remain in the markup. Please return the `x-ignore` attribute which is required for the Async Alpine script.

File: packages/forms/resources/js/components/textarea.js [hunk 1]
```diff
@@ -10,5 +10,22 @@ export default function textareaFormComponent({ initialHeight }) {
...
+            },
+            ['@resize.window']() {
+                this.render()
+            },
+            ['@form-validation-error.window']() {
+                this.$nextTick(() => {
+                    this.render()
+                })
+            },
+        },
```
Comment (zepfietje) [inline packages/forms/resources/js/components/textarea.js]: What's the reason for moving these into the JS file? 🙂

**Comment by danharrin** [comment]
Please make changes as per our comments before you request a review

File: packages/forms/resources/views/components/textarea.blade.php [hunk 2]
```diff
@@ -46,6 +46,8 @@
                 x-intersect.once="render()"
                 x-on:input="render()"
                 x-on:resize.window="render()"
+                x-on:form-validation-error.window = '$nextTick(() => render())'
```
Comment (danharrin) [inline packages/forms/resources/views/components/textarea.blade.php]:
```suggestion
                x-on:form-validation-error.window="$nextTick(() => render())"
```

File: packages/forms/resources/js/components/textarea.js (hunk 1 above)
Comment (emamalias) [reply packages/forms/resources/js/components/textarea.js]: it is not necessarily moving these in to js file indeed, but as per `resources/js/components/tags-input.js` using x-bind property, for me it is a best practice to implement that way :)

File: packages/forms/resources/views/components/textarea.blade.php [hunk 3]
```diff
@@ -44,8 +44,10 @@
                 x-data="textareaFormComponent({ initialHeight: @js($initialHeight) })"
                 x-ignore
                 x-intersect.once="render()"
+                x-on:form-validation-error.window="$nextTick(() => render())"
```
Comment (zepfietje) [inline packages/forms/resources/views/components/textarea.blade.php:47]: Is this line really needed, @danharrin @emamalias?
Same for the line above it.

Comment (emamalias) [reply packages/forms/resources/views/components/textarea.blade.php:47]: I'm not sure if we can remove `x-intersect` yet, but both attributes are not needed :) seems like the `wire:ignore.style.height` does the work. I'll make the change. thanks

Comment (emamalias) [reply packages/forms/resources/views/components/textarea.blade.php:47]: Tested with this:

```php
Forms\Components\Textarea::make('Test Textarea')
        ->prohibited()
        //->live(debounce: 500)
        ->afterStateUpdated(fn (Forms\Components\Textarea $component) =>
            $component->isLive() && $this->validateOnly($component->getStatePath())
        )
        ->autosize()
``` 
Works with/without live validation


https://github.com/filamentphp/filament/assets/13638285/45963199-3050-40e0-acc8-be9f4bbb8dc6

#
