### PR TITLE
Fix for bug #12392

### LINKED ISSUE #12392: Disabling 'attachFiles' does not prevent files from being attached (MarkdownEditor/RichEditor)
### Package

filament/filament

### Package Version

v3.2.70

### Laravel Version

v11.4.0

### Livewire Version

v3.4.10

### PHP Version

8.3

### Problem description

When adding `'attachFiles'` to the `disableToolbarButtons([...])`, file upload functionality is still present allowing a user to still upload a file (via drag/drop, copy/paste, etc).

(Side note, you need to update your issue template repo as it contains duplicate tables, references to Sanctum which isn't installed, etc).

### Expected behavior

Disabling `'attachFiles'` should inhibit a file upload from occurring. Could result in some newer developers making mistakes when implementing as it's not documented that disabling the item in the tool bar does not inhibit the action (I understand the method call specifically mentions toolbar buttons).

### Steps to reproduce

Create a new form with the following field:

```php
Forms\Components\MarkdownEditor::make('text')
    ->disableToolbarButtons(['attachFiles']),
Forms\Components\RichEditor::make('text')
    ->disableToolbarButtons(['attachFiles']),
```

You can still drag and drop a file and it will successfully upload.

### Reproduction repository

https://github.com/ZacharyDuBois/filament-file-upload-issue

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dmitry-udod**
## Description

Fix for bug #12392 (Disable the ability to upload files with drag & drop when the 'attachFiles' button is not present in the editor.)

## Visual changes

Nope

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/forms/resources/js/components/markdown-editor.js [hunk 1]
```diff
@@ -92,6 +92,7 @@ export default function markdownEditorFormComponent({
     state,
     translations,
     toolbarButtons,
+    uploadFileAllowed,
```
Comment (danharrin) [inline packages/forms/resources/js/components/markdown-editor.js]: Please rename this to canAttachFiles and reorder it so its still in alphabetical order in the arg lists

**Review by danharrin — CHANGES_REQUESTED** [review]

File: packages/forms/resources/js/components/markdown-editor.js (hunk 1 above)
Comment (dmitry-udod) [reply packages/forms/resources/js/components/markdown-editor.js]: Hello! Done.

**Review by danharrin — APPROVED** [review]
