### PR TITLE
fix: handle state type check to allow array in SpatieTagsColumn

### LINKED ISSUE #18149: In 4.x, Spatie Tags plugin doesn't display tags on a relationship properly
### Package

filament/spatie-laravel-tags-plugin

### Package Version

4.1.6

### Laravel Version

12.33.0

### Livewire Version

3.6.4

### PHP Version

PHP 8.4.13

### Problem description

On Filament 3, this would work fine:

```
                SpatieTagsColumn::make('linkedModels.tags')
                    ->type('linked')
                    ->label('Linked Tags'),
```

After upgrading to Filament 4, it shows the raw model for each of the linked tags.

Image

### Expected behavior

Show the tag name->en text, not the full model.

### Steps to reproduce

* Create two models with a relationship
* On the child model, add Spatie tags
* On the table for the main model, reference SpatieTagsColumn::make('child.tags')
* View the table

With the repository below (make sure you have sqlite available for php):
```
git clone https://github.com/natecarlson/filament-4.x-spatie-tag-relationship-issue
composer install ; npm install
cp .env.example .env ; php artisan key:generate
php artisan migrate ; php artisan db:seed
php artisan serve --port=8100
```
Connect to http://localhost:8100/admin/main-models; log in as test@example.com, password is password. You will see the busted up tags.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/natecarlson/filament-4.x-spatie-tag-relationship-issue

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by People-Sea**
## Description

fixes: #18149 

The association relationship is returned as an array, which results in no subsequent code being executed

## Visual changes

image

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php [hunk 1]
```diff
@@ -31,7 +31,7 @@ public function getState(): array
         return $this->cacheState(function (): array {
             $state = parent::getState();
 
-            if ($state && (! $state instanceof Collection)) {
+            if ($state && (! $state instanceof Collection) && ! is_array($state)) {
```
Comment (danharrin) [inline packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php]:
```suggestion
            if ($state && (! $state instanceof Collection) && (! is_array($state))) {
```

**Review by danharrin — CHANGES_REQUESTED** [review]

**Review by danharrin — APPROVED** [review]

**Comment by People-Sea** [comment]
I remember to reverse and add parentheses next time!

**Comment by danharrin** [comment]
It doesn't affect behaviour in this case, I just like parentheses when grouping conditions that contain ` ` to make the logical grouping very clear.

**Comment by People-Sea** [comment]
i see
