### PR TITLE
fix: error when only resources are configured for multi-tenancy and the authenticated user has no tenant

### LINKED ISSUE #17952: "Missing parameter: tenant" error when try to redirect on route filament.admin.tenant.registration
### Package

filament/filament

### Package Version

v4.0.20

### Laravel Version

v12.31.1

### Livewire Version

v3.6.4

### PHP Version

PHP 8.4

### Problem description

When using the tenant() and tenantRegistration() methods in Filament\Panel, an error occurs when redirecting to the "admin/new" page (filament.admin.tenant.registration).

Image

### Expected behavior

Redirect to the admin/new (create tenant form) page whitout error

Image

### Steps to reproduce

1. Create simple Filamant Panel with tenancy using the documentation [https://filamentphp.com/docs/4.x/users/tenancy]
2. Comment out methods: discoverResources(), discoverPages(), pages(), discoverWidgets(), widgets() in Filament\Panel
3. Add a resource using the resources() method
4. Create a test user
5. Try to log in

Imageithoutn

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Arthur-Zaripov/filament-tenancy-error

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by People-Sea**
## Description

Fixes:  #17952 

The error occurs when pages are specified using only `->resources`: when entering the homepage, if multi-tenancy is enabled a tenant must be present to access the homepage; otherwise it is not required.

## Visual changes

# Before

https://github.com/user-attachments/assets/de92d6d4-8662-46fe-9264-43569791117c

# After

https://github.com/user-attachments/assets/84ea5aba-6917-4505-b458-79fbdc39ff24

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/panels/src/Panel/Concerns/HasRoutes.php [hunk 1]
```diff
@@ -179,7 +179,7 @@ public function getUrl(?Model $tenant = null): ?string
             return $this->getRedirectUrl($tenant);
         }
 
-        if (Route::has($homeRouteName = $this->generateRouteName('home'))) {
+        if ((! $hasTenancy || $tenant) && Route::has($homeRouteName = $this->generateRouteName('home'))) {
```
Comment (danharrin) [inline packages/panels/src/Panel/Concerns/HasRoutes.php]: Just for extra clarity where the `!` applies

```suggestion
        if (((! $hasTenancy) || $tenant) && Route::has($homeRouteName = $this->generateRouteName('home'))) {
```

**Review by danharrin — APPROVED** [review]
