### PR TITLE
fix: Handle Empty State for KeyValueEntry

### LINKED ISSUE #11127: Infolist KeyValueEntry handles state with value empty array as NULL
### Package

filament/filament

### Package Version

v3.2.16

### Laravel Version

v10.42.0

### Livewire Version

_No response_

### PHP Version

PHP 8.3.1

### Problem description

I am trying to hook up a KeyValueEntry to an Infolist view to preview the set of properties on a given Product model, and experiencing an exception in cases where the properties list is set to **`[]`** within the DB table
It looks like the component attempts to set the `state` value to `null` in case the attribute value was returned as `[]`

> The model attribute `properties` exists within the casts array inside the model.
```php
protected $casts = [
     'properties' => ['array']
];
```

I have checked the [docs](https://filamentphp.com/docs/3.x/infolists/entries/key-value) and found nothing special about optional values and empty states

Here is the exception I am getting:
image

Here is a video of the issue:

https://github.com/filamentphp/filament/assets/21292175/01b23d05-8e54-4ef7-9c13-55a7f9cdb4be

### Expected behavior

The component should set the `state` to an empty array instead of `null`.
This way this line: `vendor/filament/infolists/resources/views/components/key-value-entry.blade.php:33` won't throw an exception

**Nice to Have**
The component should have an empty state. I've tried to override the `state` and update the `null` value to `[]` by overriding the `getState()` method on the `KeyValueEntry` component
```php
public function getState(): mixed
    {
        $state = parent::getState();

        if ($state === null) {
            return [];
        }

        if (is_array($state)) {
            return collect($state);
        }

        if ($state instanceof Collection) {
            return $state;
        }

        return $state;
    }
```
But the UI does not look like nice as a Table with only the header will be shown:
image

It would be nice if the template handles a beautiful empty state
```html
@if($getState)
      {{-- Existing logic stays as is--}}
@else
       <tr>
           <td class="px-3 py-2 text-center text-sm font-medium text-gray-700 dark:text-gray-200"
                        colspan="2">
                        {{$getEmptyLabel()}}
            </td>
        </tr>
@endif
```
image

### Steps to reproduce

The steps to re-produce are as follows:

- Create a Simple model ie, `Product` with a `not null` json attribute
- Cast the model attribute to `array`
- Create a Fillament resource for the Model
- Create a View Page (Infolist Panel) for the resource and link it to the resource pages
- Remove the edit page so that any record will redirect you to the `view` page route
```php
public static function getPages(): array
    {
        return [
            'index' => Pages\ListProducts::route('/'),
            'create' => Pages\CreateProduct::route('/create'),
            //'edit' => Pages\EditProduct::route('/{record}/edit'),
            'view' => Pages\ViewProduct::route('/{record}'),
        ];
    }
```
- Seed a Product with `properties` equal to `[]`
- Visit the products list and click on the product with no properties
- Observe the exception

### Reproduction repository

https://github.com/jafar-albadarneh/filament-keyvalue-entry-issue

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jafar-albadarneh**
## Description

Currently, `KeyValueEntry` handles empty arrays `[]` as  `null` state very well. 
The case happens when the model attribute is optional and its value is an empty array `[]`. 
More about the issue is described [here](https://github.com/filamentphp/filament/issues/11127) 

- [ * ] Visual changes (if any) are shown using screenshots/recordings of before and after.

***Before***
image

***After***
image

## Code style

- [x] `composer cs` command has been run.

## Testing

- [X] Changes have been tested.

## Documentation

- [X] Documentation is up-to-date.

### CODE REVIEW

**Comment by sandersjj** [comment]
[This bug report ](https://github.com/filamentphp/filament/issues/11128) might be releated.

File: packages/infolists/src/Components/KeyValueEntry.php [hunk 1]
```diff
@@ -15,6 +16,23 @@ class KeyValueEntry extends Entry
...
+        if ($state === null) {
+            return collect();
+        }
+
+        if (is_array($state)) {
+            return collect($state);
+        }
+
+        return $state;
+    }
```
Comment (danharrin) [inline packages/infolists/src/Components/KeyValueEntry.php]: Could you please explain what this override is being used for? I think we should avoid it if possible

Comment (jafar-albadarneh) [reply packages/infolists/src/Components/KeyValueEntry.php]: @danharrin Of course, for some reason the state of the casted array attribute is being converted to `null`, thus causing the @foreach to fail within the template.
I tried my best to track where the value of the state being overwritten and set to `null` when it's `[]`
The proposed override attempts to change the state to `[]` when it's null.

You might have a good point about avoiding such an override since the template now checks for the state value before attempting the loop.
```php
@if($getState())
```

Comment (danharrin) [reply packages/infolists/src/Components/KeyValueEntry.php]: `@if (filled($state = ($getState() ?? [])))`, `@foreach ($state ...`

Comment (jafar-albadarneh) [reply packages/infolists/src/Components/KeyValueEntry.php]: @danharrin yeah sounds better. What's your take on the empty state template change?

**Comment by danharrin** [comment]
What about it? My only comment would be renaming `label` to `message`, probably

File: packages/infolists/src/Components/KeyValueEntry.php (hunk 1 above)
Comment (danharrin) [reply packages/infolists/src/Components/KeyValueEntry.php]: What about it? My only comment would be renaming label to message, probably

File: packages/infolists/docs/03-entries/06-key-value.md [hunk 2]
```diff
@@ -51,3 +51,14 @@ use Filament\Infolists\Components\KeyValueEntry;
 KeyValueEntry::make('meta')
     ->valueLabel('Property value')
 ```
+
+## Customizing the empty value pair's label
+
+You may customize the message for empty value pairs using the `emptyMessage()` method:
```
Comment (danharrin) [inline packages/infolists/docs/03-entries/06-key-value.md]:
```suggestion
## Customizing the empty message

You may customize the message that is displayed when the entry is empty using the `emptyMessage()` method:
```

**Comment by danharrin** [comment]
Thank you for picking up on our code style and structure, and trying to make this fit into the rest of the framework as well as possible. It is appreciated!

**Comment by danharrin** [comment]
Realised this is actually just placeholder() like the other entries, so renamed to that

**Comment by jafar-albadarneh** [comment]
Makes complete sense
