### PR TITLE
[4.x] Fix `FileUpload` not working inside collapsed Repeater

### LINKED ISSUE #16253: FileUpload doesn't work as intended in Repeater of Relation Manager
### Package

filament/filament

### Package Version

v3.3.14

### Laravel Version

v12.13.0

### Livewire Version

_No response_

### PHP Version

8.2

### Problem description

I have Brand Resource with Categories Relation Manager.

In Categories Relation Manager, I have repeater for Menu Items that has File Upload for image.

After submitting the form:
It doesn't let me click on the 'x' button to remove the image. 
Also when changing the image, it doesn't work. Need to upload the image twice.

### Expected behavior

On clicking 'x' it should remove the image as it does normally.
Uploading image on edit should work as intended.

### Steps to reproduce

Use the repo I created.
In that first create a brand, then create category with menu items.
Now upload image for 1 menu item and save.
Now open the same category with menu item and try removing the image. Doesn't work.
Now try to change the image of that menu item, there will be an issue. Need to upload the same image twice.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/faizanakbar10/filament-fileupload-repeater-issue

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by People-Sea**
### Fixes: #16253

FilePond calculates layout dimensions on init. When inside a collapsed Repeater (`display: none`), all dimensions are 0, causing mispositioned elements and broken interactions.

Fix: Defer initialization until the element becomes visible.

### Before

https://github.com/user-attachments/assets/93e17f0c-5649-4917-bf4d-b463871d216f

### After

https://github.com/user-attachments/assets/55b4c298-1267-4621-b677-98d927546ea9

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

File: packages/forms/resources/js/components/file-upload.js [hunk 1]
```diff
@@ -104,7 +104,25 @@ export default function fileUploadFormComponent({
...
         editor: {},
 
+        visibilityObserver: null,
+
         async init() {
+            if (this.pond) {
+                return
+            }
+
+            if (this.$el.offsetParent === null) {
```
Comment (danharrin) [inline packages/forms/resources/js/components/file-upload.js:114]: The only thing I can think of is maybe add `this.visibilityObserver?.disconnect()` again above here, so that if the component is initialised by Alpine at some point again when the observer is already registered, we don't have two instances active at once?

Apart from that, this looks like a great solution to the problem, thanks!

**Review by danharrin — CHANGES_REQUESTED** [review]

**Comment by danharrin** [comment]
Maybe it's worth checking if this fixes issue #15394 too, since its a bit of a similar problem?

**Comment by People-Sea** [comment]
> Maybe it's worth checking if this fixes issue #15394 too, since its a bit of a similar problem?

@danharrin Thanks for the heads up! Will check if this resolves #15394 as well. ❤️
